# It all started with a lake
**and a dream**   


Wetlands are important to society, yet over half the global wetland area has been lost due to drainage, filling, native vegetation removal, invasive species, and hydrologic alterations.  Restoration of wetlands is critical to recover lost ecosystem functions and services.  Reestablishing native plant communities that contribute to ecosystem functioning is an important part of this process.  Lacustrine wetlands, particularly those in the semi-arid Intermountain West region of the U.S., have experienced extensive hydrological alterations.  They have sustained substantial water diversions and are commonly utilized as reservoirs, resulting in extreme changes in water levels that impact lakeshore vegetation.

One highly altered system is Utah Lake, the location of my proposed research, in central Utah, USA.  Utah Lake has vastly fluctuating water levels, and in some places, high wave energy and a large fetch.  These dynamic wetland conditions challenge land managers aiming to reestablish lakeshore vegetation, particularly after removal of invasive vegetation. 

My research focuses on revegetation techniques. In this bookdown I suggest that by installing wave break structures on the shoreline of the lake to dissipate wave energy, and by planting in a 'clumped' planting arrangement, you can increase the success and survival of your plant species.